; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "LogiLink1 (School)"
#define MyAppVerName "LogiLink 1.0"
#define MyAppPublisher "MasterWorks, Inc."
#define MyAppURL "http://www.masterworks.be"
#define MyAppExeName "LogiLink1.exe"

[Setup]
AppName={#MyAppName}
AppVerName={#MyAppVerName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\MasterWorks\SG_link
DefaultGroupName=\MasterWorks\LogiLink1 School
OutputDir=C:\werk\logiLink1_Logicode2_setup_inno\LogiLink1_last\Schoolversie2007\setup\output
OutputBaseFilename=setupLogiLink_SG
Compression=lzma
SolidCompression=true
UsePreviousAppDir=false
UsePreviousGroup=false
EnableDirDoesntExistWarning=true

[Languages]
Name: eng; MessagesFile: compiler:Default.isl
Name: dut; MessagesFile: compiler:Languages\Dutch.isl
Name: fre; MessagesFile: compiler:Languages\French.isl

[Tasks]

[Files]
Source: ..\panelsD\*; DestDir: {app}\panelsD\; Flags: ignoreversion createallsubdirs recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ..\LogiLink1.exe; DestDir: {app}
Source: ..\LogiLink1.ini; DestDir: {app}; Flags: ignoreversion
Source: ..\secur.ini; DestDir: {app}; Flags: ignoreversion

[Icons]
Name: {group}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; WorkingDir: {app}
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}

[Run]
Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#MyAppName}}; Flags: nowait postinstall skipifsilent
